#!/bin/sh
# Verify the customizations applied to the gateway proxy via EnterpriseKgatewayParameters.
#
# Sections are grouped by mechanism:
#   Native fields  — typed, validated fields in EnterpriseKgatewayParameters
#   Overlay fields — strategic merge patches for capabilities not in the native schema

PROXY_NS="overlays"

proxy_pod() {
  kubectl get pods -n "$PROXY_NS" -l team=platform-engineering \
    -o jsonpath='{.items[0].metadata.name}' 2>/dev/null
}

printf "\n================================================================\n"
printf " Gateway Proxy Customizations — Effect Verification\n"
printf "================================================================\n"

# -----------------------------------------------------------------------
# NATIVE FIELDS
# -----------------------------------------------------------------------

printf "\n--- [Native] Custom Pod Labels (podTemplate.extraLabels) ---\n"
printf "Pods with label 'team=platform-engineering':\n\n"
kubectl get pods -n "$PROXY_NS" -l team=platform-engineering --show-labels 2>/dev/null \
  || printf "  (no pods found — is the Gateway programmed?)\n"

printf "\n--- [Native] Resource Limits (envoyContainer.resources) ---\n"
POD=$(proxy_pod)
if [ -n "$POD" ]; then
  printf "Container resources on pod %s:\n\n" "$POD"
  kubectl get pod -n "$PROXY_NS" "$POD" \
    -o jsonpath='{range .spec.containers[?(@.name=="kgateway")]}  requests : cpu={.resources.requests.cpu}  memory={.resources.requests.memory}{"\n"}  limits   : cpu={.resources.limits.cpu}  memory={.resources.limits.memory}{"\n"}{end}' \
    2>/dev/null
  printf "\n"
else
  printf "  (no proxy pod found)\n"
fi

printf "\n--- [Native] Prometheus Annotations (podTemplate.extraAnnotations) ---\n"
POD=$(proxy_pod)
if [ -n "$POD" ]; then
  kubectl get pod -n "$PROXY_NS" "$POD" -o json 2>/dev/null \
  | python3 -c '
import sys, json
data = json.load(sys.stdin)
found = {k: v for k, v in sorted(data["metadata"]["annotations"].items()) if k.startswith("prometheus.io")}
for k, v in found.items():
    print(f"  {k}: {v}")
if not found:
    print("  (none)")
'
fi

printf "\n--- [Native] HorizontalPodAutoscaler (horizontalPodAutoscaler) ---\n"
printf "HPA generated by EnterpriseKgatewayParameters:\n\n"
kubectl get hpa -n "$PROXY_NS" 2>/dev/null \
  || printf "  (no HPA in namespace %s)\n" "$PROXY_NS"

printf "\n--- [Native] PodDisruptionBudget (podDisruptionBudget) ---\n"
printf "PDB generated by EnterpriseKgatewayParameters:\n\n"
kubectl get pdb -n "$PROXY_NS" 2>/dev/null \
  || printf "  (no PDB in namespace %s)\n" "$PROXY_NS"

# -----------------------------------------------------------------------
# OVERLAY FIELDS (deploymentOverlay)
# -----------------------------------------------------------------------

printf "\n--- [Overlay] Init Container Output (deploymentOverlay.initContainers) ---\n"
printf "The 'preflight' init container ran before the proxy started:\n\n"
POD=$(proxy_pod)
if [ -n "$POD" ]; then
  kubectl logs -n "$PROXY_NS" "$POD" -c preflight 2>/dev/null \
    || printf "  (logs not available)\n"
else
  printf "  (no proxy pod found)\n"
fi

printf "\n--- [Overlay] Debug Sidecar (deploymentOverlay.containers) ---\n"
printf "The 'debug-sidecar' container runs in the same network namespace as the proxy.\n"
printf "It can reach Envoy's local admin interface on localhost:19000:\n\n"
POD=$(proxy_pod)
if [ -n "$POD" ]; then
  printf "Envoy readiness check via sidecar (wget localhost:19000/ready):\n\n"
  kubectl exec -n "$PROXY_NS" "$POD" -c debug-sidecar -- \
    wget -qO- http://localhost:19000/ready 2>/dev/null \
    && printf "\n" \
    || printf "  (sidecar exec failed — is the pod running?)\n"

  printf "\nEnvoy cluster count via sidecar (wget localhost:19000/clusters):\n\n"
  kubectl exec -n "$PROXY_NS" "$POD" -c debug-sidecar -- \
    wget -qO- http://localhost:19000/clusters 2>/dev/null \
    | head -5 \
    || printf "  (could not reach Envoy admin)\n"
else
  printf "  (no proxy pod found)\n"
fi

printf "\n================================================================\n"
printf " Done.\n"
printf "================================================================\n\n"
