apiVersion: enterprisekgateway.solo.io/v1alpha1
kind: EnterpriseKgatewayTrafficPolicy
metadata:
  name: custom-rules-waf
  namespace: waf
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: custom-rules
  entWAF:
    wafPolicyRef:
      name: custom-rules-waf
      namespace: waf
