#!/bin/sh
# mTLS demo — shows Gateway client certificate validation (Gateway API 1.5.1).
#
# Set GW_IP before running:
#   export GW_IP=$(kubectl get gateway gw -n gwapi151 -o jsonpath='{.status.addresses[0].value}')
#
# Client certs are generated by install/generate-certs.sh and saved to install/certs/.

GW_IP=${GW_IP:-$(kubectl get gateway gw -n gwapi151 -o jsonpath='{.status.addresses[0].value}')}

if [ -z "$GW_IP" ]; then
  echo "Could not determine GW_IP. Is the gateway deployed and does it have an address?"
  exit 1
fi

GW_PORT=443
HOST="mtls.example.com"
CERT_DIR="install/certs"

# ---------------------------------------------------------------------------
# 1. Request WITH a valid client cert — gateway validates the cert and proxies
#    to httpbin. Shows the full JSON response body.
# ---------------------------------------------------------------------------
printf "\n=== With valid client cert (expect httpbin /get response) ===\n"
curl -s \
  --resolve "${HOST}:${GW_PORT}:${GW_IP}" \
  --cacert "${CERT_DIR}/ca.crt" \
  --cert   "${CERT_DIR}/client.crt" \
  --key    "${CERT_DIR}/client.key" \
  "https://${HOST}:${GW_PORT}/get"

# ---------------------------------------------------------------------------
# 2. Request WITHOUT a client cert — the gateway rejects the TLS handshake
#    because mode is AllowValidOnly. Expect an SSL handshake error.
# ---------------------------------------------------------------------------
printf "\n\n=== Without client cert (expect TLS handshake failure) ===\n"
curl -v \
  --resolve "${HOST}:${GW_PORT}:${GW_IP}" \
  --cacert "${CERT_DIR}/ca.crt" \
  "https://${HOST}:${GW_PORT}/get" 2>&1
