apiVersion: v1
kind: Service
metadata:
  name: valkey-auth
  namespace: byo-redis
  labels:
    app: valkey-auth
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: valkey-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-auth
  namespace: byo-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey-auth
  template:
    metadata:
      labels:
        app: valkey-auth
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:8
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
