apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: gwextension-default-service
  namespace: kgateway-system
spec:
  from:
    - group: gateway.kgateway.dev
      kind: GatewayExtension
      namespace: default
  to:
    - group: ""
      kind: Service