apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: xlistenerset-ingress-gw-secret
  namespace: kgateway-system
spec:
  # This one is needed to allow the listenerset to reference the secret
  from:
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      namespace: ingress-gw
  to:
    - group: ""
      kind: Secret